apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DATABASE_URL: "postgresql://neondb_owner:npg_lhz2UKAZrE8G@ep-fancy-recipe-ani3yltx-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
  JWT_SECRET: "super-secret-key-for-devops-project"
