apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  DATABASE_URL: "REPLACE_WITH_DATABASE_URL"
  JWT_SECRET: "REPLACE_WITH_JWT_SECRET"
  UPLOADTHING_TOKEN: "REPLACE_WITH_UPLOADTHING_TOKEN"
  UPLOADTHING_APP_ID: "REPLACE_WITH_UPLOADTHING_APP_ID"
  UPLOADTHING_SECRET: "REPLACE_WITH_UPLOADTHING_SECRET"
