name: CI Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci


      - name: Test backend
        working-directory: backend
        run: npm test --if-present

      - name: Build backend
        working-directory: backend
        run: npm run build

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci



      - name: Build frontend
        working-directory: frontend
        run: npm run build
